# Generated by Django 3.2.5 on 2021-07-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('-timestamp',)},
        ),
    ]
