# Generated by Django 3.2.5 on 2021-07-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tweet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
